services:
  PlanetFarAway-Js:
    image: nginx:alpine
    container_name: planet-far-away-js
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - apps_net

networks:
  apps_net:
    external: true
